Fix bazelets wrong commit
i was getting this error

ERROR: error loading package '': Encountered error while reading extension
file 'gerrit_api.bzl': no such package '@com_googlesource_gerrit_bazlets//':
Missing unknown 9a31fb6c61d83a65f8ec86c0bc3f554b04702dba.
INFO: Elapsed time: 0.285s

Change-Id: I4bd44b788b0f3ec29d9cfadf70415571d006cffd